### ISSUE TITLE
gax-java(mac): Flakey ScheduledRetryingExecutorTest.testCancelOuterFutureBeforeStart

### ISSUE THREAD

**Issue by burkedavison** [googleapis/gapic-generator-java#1342] opened 2023-02-09 13:53 UTC
Test [flaked](https://github.com/googleapis/gapic-generator-java/actions/runs/4130064207/jobs/7136363769) during nightly run. Java 17.

```
Error:  Tests run: 30, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.284 s <<< FAILURE! - in com.google.api.gax.retrying.ScheduledRetryingExecutorTest
Error:  com.google.api.gax.retrying.ScheduledRetryingExecutorTest.testCancelOuterFutureBeforeStart[Custom retry settings: true]  Time elapsed: 0.99 s  <<< FAILURE!
org.mockito.exceptions.verification.NoInteractionsWanted: 

No interactions wanted here:
-> at com.google.api.gax.retrying.AbstractRetryingExecutorTest.testCancelOuterFutureBeforeStart(AbstractRetryingExecutorTest.java:247)
But found this interaction on mock 'tracer':
-> at com.google.api.gax.retrying.FailingCallable.call(FailingCallable.java:85)
Actually, above is the only interaction with this mock.
	at com.google.api.gax.retrying.AbstractRetryingExecutorTest.testCancelOuterFutureBeforeStart(AbstractRetryingExecutorTest.java:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```

**Comment by burkedavison** [comment] 2023-02-17 15:25
[Nightly flake](https://github.com/googleapis/gapic-generator-java/actions/runs/4199816834/jobs/7285156661) on Java 11

**Comment by burkedavison** [comment] 2023-03-01 19:23
[Flake](https://github.com/googleapis/gapic-generator-java/actions/runs/4299107315/jobs/7493970486) on Java 11

**Comment by lqiu96** [comment] 2023-03-20 22:16
I've been playing around with this locally to try and re-produce this error and I've been unable to. I've been trying to debug this from the code and this is my theory as of now:

From the docs of `Future.cancel()`:
```
Attempts to cancel execution of this task. This method has no effect if the task is already completed or cancelled, or could not be cancelled for some other reason. Otherwise, if this task has not started when cancel is called, this task should never run.
```
From the test case, the outer future should never run. But I'm guessing the source of the flake is due to:
```
The return value from this method does not necessarily indicate whether the task is now cancelled; use isCancelled.
```
There might be a gap between when the future is *actually* cancelled and when the executorService starts the (*marked as cancelled but not yet*) future. Though, I think this mostly applies to a callable that is being executed on an ExecutorService and not one that has been cancelled before running.

---
Possible fixes (unconfirmed):
1. Assert that `Future.isCancelled()` is true
2. ScheduledRetryExecutor's `submit()` returns an ApiFuture that is cancelled if the RetryingFuture is already been cancelled. 
```
      if (retryingFuture.isCancelled()) {
        return ApiFutures.immediateCancelledFuture();
      }
```

**Comment by lqiu96** [comment] 2023-03-28 21:21
Following @diegomarquezp and @blakeli0's advice in Intellij (thanks both!). I've run the tests with the mode `until failure`. 

Default:
- Fails after 64 invocations
- Fails after 2800 invocations
- Fails after 153 invocations
- Fails after 780 invocations
- Fails after 625 invocations

Assertion with `Future.isCancelled`:
- Fails after 37 invocations
- Fails after 39 invocations
- Fails after 3268 invocations
- Fails after 2688 invocations
- Fails after 164 invocations

Check that `submit()` return ApiFuture that is cancelled:
- Stopped after 10000 invocations
- Stopped after 10000 invocations
- Stopped after 10000 invocations
- Stopped after 10000 invocations
- Stopped after 10000 invocations 

Need to do a bit more digging to figure out why this is the case.

**Closed** 2023-04-14 15:58 UTC
Labels: type: bug, priority: p2
