### ISSUE TITLE
Make integration test BUILD targets more discoverable

### ISSUE THREAD

**Issue by miraleung** [googleapis/gapic-generator-java#799] opened 2021-07-28 03:42 UTC

**Comment by suztomo** [comment] 2022-03-15 22:01
@miraleung (I'm on the rotation this week) Do you think this issue is still valid? If so, would you describe the current problems caused by to the build targets not being "discoverable"?

**Comment by meltsufin** [comment] 2022-03-16 14:00
The build config has changed quite a bit in the recent months. I think this is obsolete. Closing.

**Closed by meltsufin** 2022-03-16 14:00 UTC
Labels: type: bug, priority: p2, :rotating_light:
